#TODO: fix slow php scripts, phpinidir
# consider https://github.com/litespeedtech/ols-docker-env/blob/master/docker-compose.yml
version: '3.8'
services:
  db:
    container_name: dev-wp-db-container
    build:
      context: ./db container
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: my_password
        MYSQL_USER_PASSWORD: my_password
        MYSQL_PASSWORD: my_password
        #MYSQL_DATABASE: my_database     
        MYSQL_USER: user
        MYSQL_CHARSET: utf8mb4
        MYSQL_COLLATION: utf8mb4_unicode_ci
    command: --max_allowed_packet=256M
    volumes:
        - ./app/mysql:/var/lib/mysql # persistent databases on rebuild/restart
        - ./app/logs:/var/log/mysql
    restart: always
    networks:
      - wp_dev_network
  
  php-fpm:
    container_name: dev-wp-php-fpm-container
    build:
      context: ./php container
      dockerfile: Dockerfile  
    ports:
      - 9000:9000
    volumes:
      - ./app/public_html:/var/www/html
      - ./app/logs:/var/log/php
    cap_add:
      - SYS_PTRACE # for catching slow logs
    restart: always
    networks:
      - wp_dev_network

  apache2_webserver:
    container_name: dev-wp-apache-container
    build:
      context: ./apache2 container
      dockerfile: Dockerfile    
    ports:
      - 80:80
    volumes:
      - ./app/public_html:/var/www/html
      - ./app/logs:/var/log/apache2
    depends_on:
      - db
      - php-fpm
    restart: always
    networks:
      - wp_dev_network

  phpmyadmin:
    # localhost:8081 root/MYSQL_ROOT_PASSWORD
    container_name: dev-wp-phpmyadmin-container
    image: phpmyadmin/phpmyadmin
    ports:
        - '8081:80'
    environment:
        PMA_HOST: db
        UPLOAD_LIMIT: 192M
        MAX_EXECUTION_TIME: 600
    depends_on:
        - db
    restart: always
    networks:
      - wp_dev_network

networks:
  wp_dev_network:
