#TODO: enable catching slow php scripts and use of phpinidir
version: '3.8'
services:
  db:
    container_name: dev-wp-db-container
    build:
      context: ./db container
      dockerfile: Dockerfile
    ports:
      - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: my_password
        MYSQL_USER_PASSWORD: my_password
        MYSQL_PASSWORD: my_password
        #MYSQL_DATABASE: my_database     
        MYSQL_USER: user
        MYSQL_CHARSET: utf8mb4
        MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
        - ./app/mysql:/var/lib/mysql #persistent databases on rebuild/restart
        - ./app/logs:/var/log/mysql/
    networks:
      - wp_dev_network
  
  php-fpm:
    container_name: dev-wp-php-fpm-container
    build:
      context: ./php container
      dockerfile: Dockerfile  
    ports:
      - '9000:9000'
    volumes:
      - ./app/public_html:/var/www/html
      - ./app/logs:/var/log/php/
    networks:
      - wp_dev_network

  webserver:
    container_name: dev-wp-webserver-container
    build:
      context: ./webserver container
      dockerfile: Dockerfile    
    ports:
      - '80:80'
    volumes:
      - ./app/public_html:/var/www/html
      - ./app/logs:/var/log/apache2/
    depends_on:
      - db
      - php-fpm
    networks:
      - wp_dev_network

  phpmyadmin:
    #localhost:8081 root/MYSQL_ROOT_PASSWORD
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
        - '8081:80'
    environment:
        PMA_HOST: db
        UPLOAD_LIMIT: 192M
        MAX_EXECUTION_TIME: 600
    depends_on:
        - db
    networks:
      - wp_dev_network

networks:
  wp_dev_network:
