FROM mariadb:10.6

#RUN apt-get update -y && apt-get upgrade -y

# Update the MySQL configuration file
RUN echo "[mysqld]" >> /etc/mysql/conf.d/docker.cnf
RUN echo "character_set_server=utf8mb4" >> /etc/mysql/conf.d/docker.cnf
RUN echo "collation-server=utf8mb4_unicode_ci" >> /etc/mysql/conf.d/docker.cnf

# Optional: Set the time zone
ENV TZ=Europe/Moscow

# Set appropriate file permissions
RUN chown -R mysql:mysql /docker-entrypoint-initdb.d

# Start the MariaDB service
CMD ["mysqld"]
