FROM mariadb:10.6
# https://hub.docker.com/_/mariadb
RUN apt-get update -y
RUN apt-get install htop mytop nano sudo -y
# mytop u root -p my_password -d newlepko_lepkov_shop

# Update the MySQL configuration file
RUN echo "[mysqld]" >> /etc/mysql/conf.d/docker.cnf
RUN echo "character_set_server=utf8mb4" >> /etc/mysql/conf.d/docker.cnf
RUN echo "collation-server=utf8mb4_unicode_ci" >> /etc/mysql/conf.d/docker.cnf

# Turn on slow query catch
RUN echo "slow_query_log = 1" >> /etc/mysql/conf.d/docker.cnf
RUN echo "slow_query_log_file = /var/log/mysql/mariadb-slow.log" >> /etc/mysql/conf.d/docker.cnf
RUN echo "long_query_time = 1" >> /etc/mysql/conf.d/docker.cnf

# Tune MariaDB for the Wordpress (https://www.cloudservices.store/cp/index.php/knowledgebase/63/Tune-MySQL-or-mariadb-database-for-WooCommerce-and-WordPress.html)
RUN echo "innodb_buffer_pool_size=512M" >> /etc/mysql/conf.d/docker.cnf 
# SQL QUERY TO CHECK: SHOW VARIABLES LIKE '%innodb_buffer_pool_size%';
RUN echo "query_cache_limit=8M" >> /etc/mysql/conf.d/docker.cnf 
RUN echo "query_cache_size=256M" >> /etc/mysql/conf.d/docker.cnf 
RUN echo "query_cache_type=1" >> /etc/mysql/conf.d/docker.cnf 

# Optional: Set the time zone
ENV TZ=Europe/Moscow

# Set appropriate file permissions
RUN chown -R mysql:mysql /docker-entrypoint-initdb.d

# Start the MariaDB service
CMD ["mysqld"]